version: "3"

services:
  blog:
    image: ghost
    environment:
      url: https://blog.localhost

  http:
    image: metal3d/nginx-auto:1.16-alpine
    environment:
      DOMAINS: blog.localhost:blog:2368
      SSL: "true"
      REDIRECT: "true"
      CERTS: blog.localhost:cert.pem:key.pem
    volumes:
      - ./certs:/etc/nginx/certs:z
    depends_on:
      - blog
    ports:
      - 80:80
      - 443:443
